In [1]:
!git clone https://github.com/mugen13lue/Data301FinalProject.git

Cloning into 'Data301FinalProject'...
remote: Enumerating objects: 87, done.
remote: Total 87 (delta 0), reused 0 (delta 0), pack-reused 87
Unpacking objects: 100% (87/87), done.
Checking out files: 100% (55/55), done.

In [0]:
# !cd Data301FinalProject/ ;git pull

# Doneish

# Kellie

In [1]:
import pandas as pd
import numpy as np
import os
import json
from pandas.io.json import json_normalize

dir_main = "Data301FinalProject/datasets/"
!ls $dir_main

ks_2016-04-15  ks_2016-12-15  ks_2017-08-15  ks_2018-04-12  ks_2018_12_13
ks_2016_06-15  ks_2017-02-15  ks_2017-10-15  ks_2018-06-14  ks_2019-02-14
ks_2016-08-15  ks_2017-04-15  ks_2017-12-15  ks_2018-08-16
ks_2016-10-15  ks_2017-06-15  ks_2018-02-15  ks_2018_10_18

In [0]:
dir201902 = dir_main + "ks_2019-02-14/"
ks201902 = pd.read_csv(dir201902 + "Kickstarter000.csv",
                       engine="python")
ks201902 = ks201902.drop(
    ["is_backing", "is_starrable", "is_starred", "permissions",
     "currency_symbol", "friends", "source_url", "disable_communication",
     "currency_trailing_code", "current_currency", "usd_type", "pledged",
     "static_usd_rate", "fx_rate", "photo",
     "converted_pledged_amount", "profile"],
    axis=1
)

# TODO: weren't able to successfully convert creator and location to JSON.
# dropping these cols and moving on for now, but should revisit later
ks201902 = ks201902.drop(["location", "creator"], axis=1)

In [3]:
import ast

json_cols = ["category", "urls"]
#json_cols = ["category", "creator", "photo", "urls", "location"]
# TODO: weren't able to successfully convert creator and location to JSON.
# ignoring these cols and moving on for now, but should revisit later

for col in json_cols:
  print(col)
  ks201902[col] = ks201902[col].fillna('')
  ks201902[col] = ks201902[col].apply(ast.literal_eval)
  
ks201902.head(3)

category
urls

,backers_count,blurb,category,country,created_at,currency,deadline,goal,id,launched_at,name,slug,spotlight,staff_pick,state,state_changed_at,urls,usd_pledged
0,4,Handmade glass trees that make a special Chris...,"{'id': 347, 'name': 'Glass', 'slug': 'crafts/g...",US,1464927602,USD,1466474760,1000,1145008426,1465007515,Glass Christmas Trees & Glass Cross,glass-christmas-trees-and-glass-cross,False,False,failed,1466474764,{'web': {'project': 'https://www.kickstarter.c...,205.0
1,171,Perfect pair of Socks for any Adventurer! Sock...,"{'id': 34, 'name': 'Tabletop Games', 'slug': '...",US,1540391660,USD,1542304740,2000,1687733153,1540929602,Socks of Speed and Socks of Elvenkind,socks-of-speed-and-socks-of-elvenkind,True,False,successful,1542304740,{'web': {'project': 'https://www.kickstarter.c...,6061.0
2,9,This is a Series of 6 Books on Blessed Oscar A...,"{'id': 327, 'name': 'Translations', 'slug': 'p...",US,1434584826,USD,1439741591,4400,1608693208,1436285591,The Complete Homilies of Blessed Oscar Romero:...,the-complete-homilies-of-blessed-oscar-romero-...,False,False,failed,1439741591,{'web': {'project': 'https://www.kickstarter.c...,800.0

## Clean JSON Variables

In [4]:
category_exp = json_normalize(ks201902["category"])
ks201902 = ks201902.drop("category", axis=1)
ks201902.head()

,backers_count,blurb,country,created_at,currency,deadline,goal,id,launched_at,name,slug,spotlight,staff_pick,state,state_changed_at,urls,usd_pledged
0,4,Handmade glass trees that make a special Chris...,US,1464927602,USD,1466474760,1000,1145008426,1465007515,Glass Christmas Trees & Glass Cross,glass-christmas-trees-and-glass-cross,False,False,failed,1466474764,{'web': {'project': 'https://www.kickstarter.c...,205.000000
1,171,Perfect pair of Socks for any Adventurer! Sock...,US,1540391660,USD,1542304740,2000,1687733153,1540929602,Socks of Speed and Socks of Elvenkind,socks-of-speed-and-socks-of-elvenkind,True,False,successful,1542304740,{'web': {'project': 'https://www.kickstarter.c...,6061.000000
2,9,This is a Series of 6 Books on Blessed Oscar A...,US,1434584826,USD,1439741591,4400,1608693208,1436285591,The Complete Homilies of Blessed Oscar Romero:...,the-complete-homilies-of-blessed-oscar-romero-...,False,False,failed,1439741591,{'web': {'project': 'https://www.kickstarter.c...,800.000000
3,24,Prodeus makes self employment simple and intui...,US,1493997043,USD,1498060876,50000,66308869,1495468876,Prodeus: The Future of Work & Learning,prodeus-social-network-learning-community-micr...,False,False,failed,1498060876,{'web': {'project': 'https://www.kickstarter.c...,1484.000000
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...",ES,1544546012,EUR,1550189608,700,654590050,1547165608,Dungeon Corp LTD.: The Adventures of Bob and Tim.,dungeon-corp-ltd-the-adventures-of-bob-and-tim,False,True,live,1547165608,{'web': {'project': 'https://www.kickstarter.c...,1087.667629

In [5]:
category_tups = category_exp.slug.str.split("/").apply(pd.Series)
category_tups.columns = ["parent_category", "category"]
ks201902 = pd.concat([ks201902, category_tups], axis=1)
ks201902.head()

,backers_count,blurb,country,created_at,currency,deadline,goal,id,launched_at,name,slug,spotlight,staff_pick,state,state_changed_at,urls,usd_pledged,parent_category,category
0,4,Handmade glass trees that make a special Chris...,US,1464927602,USD,1466474760,1000,1145008426,1465007515,Glass Christmas Trees & Glass Cross,glass-christmas-trees-and-glass-cross,False,False,failed,1466474764,{'web': {'project': 'https://www.kickstarter.c...,205.000000,crafts,glass
1,171,Perfect pair of Socks for any Adventurer! Sock...,US,1540391660,USD,1542304740,2000,1687733153,1540929602,Socks of Speed and Socks of Elvenkind,socks-of-speed-and-socks-of-elvenkind,True,False,successful,1542304740,{'web': {'project': 'https://www.kickstarter.c...,6061.000000,games,tabletop games
2,9,This is a Series of 6 Books on Blessed Oscar A...,US,1434584826,USD,1439741591,4400,1608693208,1436285591,The Complete Homilies of Blessed Oscar Romero:...,the-complete-homilies-of-blessed-oscar-romero-...,False,False,failed,1439741591,{'web': {'project': 'https://www.kickstarter.c...,800.000000,publishing,translations
3,24,Prodeus makes self employment simple and intui...,US,1493997043,USD,1498060876,50000,66308869,1495468876,Prodeus: The Future of Work & Learning,prodeus-social-network-learning-community-micr...,False,False,failed,1498060876,{'web': {'project': 'https://www.kickstarter.c...,1484.000000,technology,web
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...",ES,1544546012,EUR,1550189608,700,654590050,1547165608,Dungeon Corp LTD.: The Adventures of Bob and Tim.,dungeon-corp-ltd-the-adventures-of-bob-and-tim,False,True,live,1547165608,{'web': {'project': 'https://www.kickstarter.c...,1087.667629,comics,comic books

In [6]:
urls_exp = json_normalize(ks201902["urls"])
urls_exp = urls_exp[["web.project", "web.rewards"]]
urls_exp.columns = ["project_url", "rewards_url"]
urls_exp.head()

,project_url,rewards_url
0,https://www.kickstarter.com/projects/coldglass...,https://www.kickstarter.com/projects/coldglass...
1,https://www.kickstarter.com/projects/497057119...,https://www.kickstarter.com/projects/497057119...
2,https://www.kickstarter.com/projects/convivium...,https://www.kickstarter.com/projects/convivium...
3,https://www.kickstarter.com/projects/973039847...,https://www.kickstarter.com/projects/973039847...
4,https://www.kickstarter.com/projects/eternalve...,https://www.kickstarter.com/projects/eternalve...

In [7]:
ks201902 = pd.concat([ks201902, urls_exp], axis=1)
ks201902 = ks201902.drop("urls", axis=1)
ks201902.head()

,backers_count,blurb,country,created_at,currency,deadline,goal,id,launched_at,name,slug,spotlight,staff_pick,state,state_changed_at,usd_pledged,parent_category,category,project_url,rewards_url
0,4,Handmade glass trees that make a special Chris...,US,1464927602,USD,1466474760,1000,1145008426,1465007515,Glass Christmas Trees & Glass Cross,glass-christmas-trees-and-glass-cross,False,False,failed,1466474764,205.000000,crafts,glass,https://www.kickstarter.com/projects/coldglass...,https://www.kickstarter.com/projects/coldglass...
1,171,Perfect pair of Socks for any Adventurer! Sock...,US,1540391660,USD,1542304740,2000,1687733153,1540929602,Socks of Speed and Socks of Elvenkind,socks-of-speed-and-socks-of-elvenkind,True,False,successful,1542304740,6061.000000,games,tabletop games,https://www.kickstarter.com/projects/497057119...,https://www.kickstarter.com/projects/497057119...
2,9,This is a Series of 6 Books on Blessed Oscar A...,US,1434584826,USD,1439741591,4400,1608693208,1436285591,The Complete Homilies of Blessed Oscar Romero:...,the-complete-homilies-of-blessed-oscar-romero-...,False,False,failed,1439741591,800.000000,publishing,translations,https://www.kickstarter.com/projects/convivium...,https://www.kickstarter.com/projects/convivium...
3,24,Prodeus makes self employment simple and intui...,US,1493997043,USD,1498060876,50000,66308869,1495468876,Prodeus: The Future of Work & Learning,prodeus-social-network-learning-community-micr...,False,False,failed,1498060876,1484.000000,technology,web,https://www.kickstarter.com/projects/973039847...,https://www.kickstarter.com/projects/973039847...
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...",ES,1544546012,EUR,1550189608,700,654590050,1547165608,Dungeon Corp LTD.: The Adventures of Bob and Tim.,dungeon-corp-ltd-the-adventures-of-bob-and-tim,False,True,live,1547165608,1087.667629,comics,comic books,https://www.kickstarter.com/projects/eternalve...,https://www.kickstarter.com/projects/eternalve...

## Clean Timestamps

In [8]:
from datetime import datetime

timestamps = ["created_at", "state_changed_at", "launched_at", "deadline"]
for ts in timestamps:
  ks201902[ts] = ks201902[ts].apply(datetime.utcfromtimestamp)
ks201902.head()

,backers_count,blurb,country,created_at,currency,deadline,goal,id,launched_at,name,slug,spotlight,staff_pick,state,state_changed_at,usd_pledged,parent_category,category,project_url,rewards_url
0,4,Handmade glass trees that make a special Chris...,US,2016-06-03 04:20:02,USD,2016-06-21 02:06:00,1000,1145008426,2016-06-04 02:31:55,Glass Christmas Trees & Glass Cross,glass-christmas-trees-and-glass-cross,False,False,failed,2016-06-21 02:06:04,205.000000,crafts,glass,https://www.kickstarter.com/projects/coldglass...,https://www.kickstarter.com/projects/coldglass...
1,171,Perfect pair of Socks for any Adventurer! Sock...,US,2018-10-24 14:34:20,USD,2018-11-15 17:59:00,2000,1687733153,2018-10-30 20:00:02,Socks of Speed and Socks of Elvenkind,socks-of-speed-and-socks-of-elvenkind,True,False,successful,2018-11-15 17:59:00,6061.000000,games,tabletop games,https://www.kickstarter.com/projects/497057119...,https://www.kickstarter.com/projects/497057119...
2,9,This is a Series of 6 Books on Blessed Oscar A...,US,2015-06-17 23:47:06,USD,2015-08-16 16:13:11,4400,1608693208,2015-07-07 16:13:11,The Complete Homilies of Blessed Oscar Romero:...,the-complete-homilies-of-blessed-oscar-romero-...,False,False,failed,2015-08-16 16:13:11,800.000000,publishing,translations,https://www.kickstarter.com/projects/convivium...,https://www.kickstarter.com/projects/convivium...
3,24,Prodeus makes self employment simple and intui...,US,2017-05-05 15:10:43,USD,2017-06-21 16:01:16,50000,66308869,2017-05-22 16:01:16,Prodeus: The Future of Work & Learning,prodeus-social-network-learning-community-micr...,False,False,failed,2017-06-21 16:01:16,1484.000000,technology,web,https://www.kickstarter.com/projects/973039847...,https://www.kickstarter.com/projects/973039847...
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...",ES,2018-12-11 16:33:32,EUR,2019-02-15 00:13:28,700,654590050,2019-01-11 00:13:28,Dungeon Corp LTD.: The Adventures of Bob and Tim.,dungeon-corp-ltd-the-adventures-of-bob-and-tim,False,True,live,2019-01-11 00:13:28,1087.667629,comics,comic books,https://www.kickstarter.com/projects/eternalve...,https://www.kickstarter.com/projects/eternalve...

In [9]:
ks201902["project_duration"] = ks201902["deadline"] - ks201902["created_at"]
ks201902["time_til_state_changed"] = (ks201902["state_changed_at"] -
                                      ks201902["created_at"])
ks201902.head()

,backers_count,blurb,country,created_at,currency,deadline,goal,id,launched_at,name,...,staff_pick,state,state_changed_at,usd_pledged,parent_category,category,project_url,rewards_url,project_duration,time_til_state_changed
0,4,Handmade glass trees that make a special Chris...,US,2016-06-03 04:20:02,USD,2016-06-21 02:06:00,1000,1145008426,2016-06-04 02:31:55,Glass Christmas Trees & Glass Cross,...,False,failed,2016-06-21 02:06:04,205.000000,crafts,glass,https://www.kickstarter.com/projects/coldglass...,https://www.kickstarter.com/projects/coldglass...,17 days 21:45:58,17 days 21:46:02
1,171,Perfect pair of Socks for any Adventurer! Sock...,US,2018-10-24 14:34:20,USD,2018-11-15 17:59:00,2000,1687733153,2018-10-30 20:00:02,Socks of Speed and Socks of Elvenkind,...,False,successful,2018-11-15 17:59:00,6061.000000,games,tabletop games,https://www.kickstarter.com/projects/497057119...,https://www.kickstarter.com/projects/497057119...,22 days 03:24:40,22 days 03:24:40
2,9,This is a Series of 6 Books on Blessed Oscar A...,US,2015-06-17 23:47:06,USD,2015-08-16 16:13:11,4400,1608693208,2015-07-07 16:13:11,The Complete Homilies of Blessed Oscar Romero:...,...,False,failed,2015-08-16 16:13:11,800.000000,publishing,translations,https://www.kickstarter.com/projects/convivium...,https://www.kickstarter.com/projects/convivium...,59 days 16:26:05,59 days 16:26:05
3,24,Prodeus makes self employment simple and intui...,US,2017-05-05 15:10:43,USD,2017-06-21 16:01:16,50000,66308869,2017-05-22 16:01:16,Prodeus: The Future of Work & Learning,...,False,failed,2017-06-21 16:01:16,1484.000000,technology,web,https://www.kickstarter.com/projects/973039847...,https://www.kickstarter.com/projects/973039847...,47 days 00:50:33,47 days 00:50:33
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...",ES,2018-12-11 16:33:32,EUR,2019-02-15 00:13:28,700,654590050,2019-01-11 00:13:28,Dungeon Corp LTD.: The Adventures of Bob and Tim.,...,True,live,2019-01-11 00:13:28,1087.667629,comics,comic books,https://www.kickstarter.com/projects/eternalve...,https://www.kickstarter.com/projects/eternalve...,65 days 07:39:56,30 days 07:39:56

# Mugen

In [0]:
ks_02_14_19_1 = pd.read_csv("/content/Data301FinalProject/datasets/kickstarter_2019_02_14/Kickstarter001.csv")
ks_02_14_19_1.head()

,backers_count,blurb,category,converted_pledged_amount,country,created_at,creator,currency,currency_symbol,currency_trailing_code,...,slug,source_url,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged,usd_type
0,0,I'm trying to create a website with 1 million ...,"{""id"":278,""name"":""People"",""slug"":""photography/...",0,US,1442186294,"{""id"":86632001,""name"":""Dedrick Grandstaff"",""is...",USD,$,True,...,1-million-fly-outfits,https://www.kickstarter.com/discover/categorie...,False,False,canceled,1442962802,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",0.000000,international
1,6,Help the creation of a permanent repository fo...,"{""id"":24,""name"":""Performance Art"",""slug"":""art/...",821,US,1495487865,"{""id"":976005671,""name"":""The Bix Beiderbecke Mu...",USD,$,True,...,bix-beiderbecke-memorial-museum,https://www.kickstarter.com/discover/categorie...,False,False,failed,1500581701,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",821.000000,domestic
2,2,"A bar where you can go, geek out, play some ga...","{""id"":307,""name"":""Drinks"",""slug"":""food/drinks""...",135,GB,1465149859,"{""id"":600775163,""name"":""Josh Sutton"",""is_regis...",GBP,£,False,...,the-kaiju-arena,https://www.kickstarter.com/discover/categorie...,False,False,failed,1471201913,1.418782,"{""web"":{""project"":""https://www.kickstarter.com...",148.972092,domestic
3,1,Our multi award winning Reposado Tequila is re...,"{""id"":307,""name"":""Drinks"",""slug"":""food/drinks""...",1,US,1424114900,"{""id"":1954307886,""name"":""Michael Scott Fladset...",USD,$,True,...,tequila-brand-reposado-100-blue-agave-double-d...,https://www.kickstarter.com/discover/categorie...,False,False,failed,1426870864,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",1.000000,domestic
4,1,"I like to annoy Adam, I need money for a pie t...","{""id"":294,""name"":""Experimental"",""slug"":""film &...",1,GB,1417104803,"{""id"":148243949,""name"":""Jason Franklin"",""is_re...",GBP,£,False,...,pie-in-the-face-of-adam,https://www.kickstarter.com/discover/categorie...,False,False,failed,1420072078,1.564857,"{""web"":{""project"":""https://www.kickstarter.com...",1.564857,domestic

In [0]:
import pandas as pd

ks_02_14_19 = pd.read_csv("/content/Data301FinalProject/datasets/kickstarter_2019_02_14/Kickstarter000.csv")
ks_02_14_19.head()

,backers_count,blurb,category,converted_pledged_amount,country,created_at,creator,currency,currency_symbol,currency_trailing_code,...,slug,source_url,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged,usd_type
0,4,Handmade glass trees that make a special Chris...,"{""id"":347,""name"":""Glass"",""slug"":""crafts/glass""...",205,US,1464927602,"{""id"":661261267,""name"":""Mark & Julie Glocke"",""...",USD,$,True,...,glass-christmas-trees-and-glass-cross,https://www.kickstarter.com/discover/categorie...,False,False,failed,1466474764,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",205.000000,domestic
1,171,Perfect pair of Socks for any Adventurer! Sock...,"{""id"":34,""name"":""Tabletop Games"",""slug"":""games...",6061,US,1540391660,"{""id"":497057119,""name"":""Andy ""Cosmo-Joe"" Watki...",USD,$,True,...,socks-of-speed-and-socks-of-elvenkind,https://www.kickstarter.com/discover/categorie...,True,False,successful,1542304740,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",6061.000000,international
2,9,This is a Series of 6 Books on Blessed Oscar A...,"{""id"":327,""name"":""Translations"",""slug"":""publis...",800,US,1434584826,"{""id"":267701790,""name"":""Convivium Press"",""slug...",USD,$,True,...,the-complete-homilies-of-blessed-oscar-romero-...,https://www.kickstarter.com/discover/categorie...,False,False,failed,1439741591,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",800.000000,domestic
3,24,Prodeus makes self employment simple and intui...,"{""id"":342,""name"":""Web"",""slug"":""technology/web""...",1484,US,1493997043,"{""id"":973039847,""name"":""James Harr"",""is_regist...",USD,$,True,...,prodeus-social-network-learning-community-micr...,https://www.kickstarter.com/discover/categorie...,False,False,failed,1498060876,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",1484.000000,domestic
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...","{""id"":250,""name"":""Comic Books"",""slug"":""comics/...",1066,ES,1544546012,"{""id"":496847178,""name"":""Eternalverse"",""slug"":""...",EUR,€,False,...,dungeon-corp-ltd-the-adventures-of-bob-and-tim,https://www.kickstarter.com/discover/categorie...,False,True,live,1547165608,1.155864,"{""web"":{""project"":""https://www.kickstarter.com...",1087.667629,domestic

In [0]:
ks201902.head()

,backers_count,blurb,category,converted_pledged_amount,country,created_at,creator,currency,currency_trailing_code,current_currency,...,profile,slug,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged,usd_type
0,4,Handmade glass trees that make a special Chris...,"{""id"":347,""name"":""Glass"",""slug"":""crafts/glass""...",205,US,1464927602,"{""id"":661261267,""name"":""Mark & Julie Glocke"",""...",USD,True,USD,...,"{""id"":2543897,""project_id"":2543897,""state"":""in...",glass-christmas-trees-and-glass-cross,False,False,failed,1466474764,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",205.000000,domestic
1,171,Perfect pair of Socks for any Adventurer! Sock...,"{""id"":34,""name"":""Tabletop Games"",""slug"":""games...",6061,US,1540391660,"{""id"":497057119,""name"":""Andy ""Cosmo-Joe"" Watki...",USD,True,USD,...,"{""id"":3498932,""project_id"":3498932,""state"":""in...",socks-of-speed-and-socks-of-elvenkind,True,False,successful,1542304740,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",6061.000000,international
2,9,This is a Series of 6 Books on Blessed Oscar A...,"{""id"":327,""name"":""Translations"",""slug"":""publis...",800,US,1434584826,"{""id"":267701790,""name"":""Convivium Press"",""slug...",USD,True,USD,...,"{""id"":1965582,""project_id"":1965582,""state"":""in...",the-complete-homilies-of-blessed-oscar-romero-...,False,False,failed,1439741591,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",800.000000,domestic
3,24,Prodeus makes self employment simple and intui...,"{""id"":342,""name"":""Web"",""slug"":""technology/web""...",1484,US,1493997043,"{""id"":973039847,""name"":""James Harr"",""is_regist...",USD,True,USD,...,"{""id"":2988723,""project_id"":2988723,""state"":""in...",prodeus-social-network-learning-community-micr...,False,False,failed,1498060876,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",1484.000000,domestic
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...","{""id"":250,""name"":""Comic Books"",""slug"":""comics/...",1066,ES,1544546012,"{""id"":496847178,""name"":""Eternalverse"",""slug"":""...",EUR,False,USD,...,"{""id"":3533340,""project_id"":3533340,""state"":""in...",dungeon-corp-ltd-the-adventures-of-bob-and-tim,False,True,live,1547165608,1.155864,"{""web"":{""project"":""https://www.kickstarter.com...",1087.667629,domestic

In [0]:
datetime(1970, 1, 1)

datetime.datetime(1970, 1, 1, 0, 0)

In [0]:
from datetime import datetime, timedelta

#ks201902["created_at"] = ks201902["created_at"]* 1e-3
#ks201902["created_at"] = ks201902["created_at"].add(datetime(1970, 1, 1))
ks201902["created_at"] = ks201902["created_at"].apply(datetime.utcfromtimestamp)
#ks201902["created_at"] = datetime(1970, 1, 1) + ks201902["created_at"]
#ks201902["state_changed_at"] = ks201902["state_changed_at"]* 1e-3
ks201902["state_changed_at"] = ks201902["state_changed_at"].apply(datetime.utcfromtimestamp)
#ks201902["launched_at"] = ks201902["launched_at"]* 1e-3
ks201902["launched_at"] = ks201902["launched_at"].apply(datetime.utcfromtimestamp)
#ks201902["deadline"] = ks201902["deadline"]* 1e-3
ks201902["deadline"] = ks201902["deadline"].apply(datetime.utcfromtimestamp)

In [0]:
ks201902["creation_deadline"] = ks201902["deadline"] - ks201902["created_at"]
ks201902["start_change"]

In [0]:
ks201902[["created_at", "state_changed_at", "launched_at", "deadline", "change_in_time"]]

,created_at,state_changed_at,launched_at,deadline,change_in_time
0,2016-06-03 04:20:02,2016-06-21 02:06:04,2016-06-04 02:31:55,2016-06-21 02:06:00,17 days 21:45:58
1,2018-10-24 14:34:20,2018-11-15 17:59:00,2018-10-30 20:00:02,2018-11-15 17:59:00,22 days 03:24:40
2,2015-06-17 23:47:06,2015-08-16 16:13:11,2015-07-07 16:13:11,2015-08-16 16:13:11,59 days 16:26:05
3,2017-05-05 15:10:43,2017-06-21 16:01:16,2017-05-22 16:01:16,2017-06-21 16:01:16,47 days 00:50:33
4,2018-12-11 16:33:32,2019-01-11 00:13:28,2019-01-11 00:13:28,2019-02-15 00:13:28,65 days 07:39:56
5,2018-07-25 14:06:52,2018-09-05 10:00:43,2018-08-06 10:00:43,2018-09-05 10:00:43,41 days 19:53:51
6,2017-05-15 21:52:57,2017-07-09 15:41:04,2017-06-09 15:41:03,2017-07-09 15:41:03,54 days 17:48:06
7,2014-08-30 20:54:40,2014-11-10 06:00:13,2014-09-25 18:46:01,2014-11-10 06:00:00,71 days 09:05:20
8,2016-02-21 13:54:48,2017-01-27 16:35:11,2016-11-28 16:35:11,2017-01-27 16:35:11,341 days 02:40:23
9,2018-10-22 12:13:01,2019-01-27 11:19:22,2018-12-13 11:19:22,2019-01-27 11:19:22,96 days 23:06:21
10,2016-02-03 22:12:19,2016-03-11 16:33:18,2016-02-10 16:33:18,2016-03-11 16:33:18,36 days 18:20:59
11,2013-10-24 00:21:11,2014-02-21 18:21:37,2014-01-22 18:21:37,2014-02-21 18:21:37,120 days 18:00:26
12,2019-01-19 01:58:25,2019-01-31 18:31:36,2019-01-31 18:31:35,2019-03-02 18:31:35,42 days 16:33:10
13,2018-08-13 02:20:13,2018-09-16 18:58:18,2018-08-17 18:58:18,2018-09-16 18:58:18,34 days 16:38:05
14,2018-05-25 17:18:37,2018-08-16 21:36:14,2018-07-17 21:36:14,2018-08-16 21:36:14,83 days 04:17:37
15,2011-09-13 14:43:38,2011-10-17 17:02:56,2011-09-17 17:02:56,2011-10-17 17:02:56,34 days 02:19:18
16,2013-01-17 15:23:41,2013-04-30 16:01:17,2013-03-01 17:01:17,2013-04-30 16:01:17,103 days 00:37:36
17,2017-09-02 17:23:38,2017-10-05 14:21:05,2017-09-05 14:21:05,2017-10-05 14:21:05,32 days 20:57:27
18,2015-02-19 22:16:40,2015-04-22 01:30:12,2015-04-02 11:11:32,2015-04-22 01:30:00,61 days 03:13:20
19,2018-07-03 02:59:10,2018-08-30 18:00:01,2018-07-30 17:03:03,2018-08-30 18:00:00,58 days 15:00:50
20,2018-08-03 21:23:25,2019-02-04 01:20:12,2018-12-06 01:20:12,2019-02-04 01:20:12,184 days 03:56:47
21,2013-03-12 17:04:00,2013-04-19 23:45:37,2013-03-20 23:45:37,2013-04-19 23:45:37,38 days 06:41:37
22,2015-01-25 17:26:05,2015-02-07 23:00:12,2015-01-29 22:27:36,2015-02-07 23:00:00,13 days 05:33:55
23,2014-06-24 23:32:46,2014-08-07 16:20:23,2014-06-26 21:10:57,2014-08-10 21:10:57,46 days 21:38:11
24,2015-04-09 18:36:58,2015-06-04 12:38:23,2015-04-29 12:38:21,2015-06-04 12:38:21,55 days 18:01:23
25,2014-08-24 16:50:19,2014-09-22 03:00:11,2014-08-28 00:41:00,2014-09-22 03:00:00,28 days 10:09:41
26,2012-11-15 23:25:55,2012-12-24 20:05:20,2012-11-30 20:05:17,2012-12-24 20:05:17,38 days 20:39:22
27,2018-05-19 14:17:27,2018-06-25 16:06:30,2018-06-04 16:06:30,2018-06-25 16:06:30,37 days 01:49:03
28,2018-12-27 20:20:04,2018-12-27 22:19:17,2018-12-27 22:19:17,2019-02-25 07:00:00,59 days 10:39:56
29,2016-09-14 10:03:43,2016-10-15 16:09:39,2016-09-15 16:09:39,2016-10-15 16:09:39,31 days 06:05:56
...,...,...,...,...,...
3792,2018-05-25 18:50:46,2018-07-15 16:29:30,2018-06-25 16:29:27,2018-07-15 16:29:27,50 days 21:38:41
3793,2013-04-15 15:58:59,2013-05-23 15:38:06,2013-04-23 15:38:05,2013-05-23 15:38:05,37 days 23:39:06
3794,2011-06-22 01:21:26,2011-08-08 22:24:42,2011-06-29 22:24:39,2011-08-08 22:24:39,47 days 21:03:13
3795,2015-03-18 22:26:06,2015-05-01 05:59:03,2015-03-24 17:46:55,2015-05-01 05:59:00,43 days 07:32:54
3796,2015-11-19 19:33:55,2015-12-30 23:54:18,2015-11-24 23:53:38,2015-12-30 23:53:38,41 days 04:19:43
3797,2015-01-20 02:43:50,2018-07-31 07:50:57,2018-07-01 07:50:56,2018-07-31 07:50:56,1288 days 05:07:06
3798,2015-05-07 20:30:19,2015-07-08 04:59:00,2015-06-16 05:33:48,2015-07-08 04:59:00,61 days 08:28:41
3799,2016-04-11 19:12:13,2016-06-13 05:27:01,2016-05-16 05:45:09,2016-06-13 05:27:00,62 days 10:14:47
3800,2014-05-13 22:54:17,2014-06-21 03:59:02,2014-05-21 23:02:20,2014-06-21 03:59:00,38 days 05:04:43
3801,2015-06-11 18:19:10,2015-10-15 19:21:15,2015-09-15 19:21:15,2015-10-15 19:21:15,126 days 01:02:05
3802,2014-08-18 12:59:17,2014-09-27 23:57:27,2014-08-18 23:57:25,2014-09-27 23:57:25,40 days 10:58:08
3803,2018-07-02 07:46:50,2018-07-29 22:59:02,2018-07-16 18:38:33,2018-07-29 22:59:00,27 days 15:12:10
3804,2011-05-07 23:35:52,2011-07-18 16:09:54,2011-06-18 16:09:54,2011-07-18 16:09:54,71 days 16:34:02
3805,2015-09-28 17:00:03,2015-10-29 15:49:44,2015-09-29 15:49:42,2015-10-29 15:49:42,30 days 22:49:39
3806,2012-07-25 14:40:53,2012-09-01 19:22:43,2012-08-02 19:22:40,2012-09-01 19:22:40,38 days 04:41:47
3807,2015-02-16 19:37:48,2015-04-06 00:04:21,2015-02-20 01:04:19,2015-04-06 00:04:19,48 days 04:26:31
3808,2012-09-22 17:32:41,2013-04-06 15:31:45,2013-03-22 15:31:44,2013-04-06 15:31:44,195 days 21:59:03
3809,2018-07-28 21:48:28,2018-09-11 18:00:02,2018-08-13 11:04:34,2018-09-11 18:00:00,44 days 20:11:32
3810,2017-03-30 02:43:41,2017-07-18 02:18:25,2017-06-18 02:18:25,2017-07-18 02:18:25,109 days 23:34:44
3811,2014-07-09 11:32:19,2014-08-20 23:51:54,2014-07-21 23:51:54,2014-08-20 23:51:54,42 days 12:19:35
3812,2014-10-07 09:11:57,2015-05-21 04:13:38,2015-03-22 04:13:35,2015-05-21 04:13:35,225 days 19:01:38
3813,2014-11-04 17:41:58,2014-12-14 11:01:18,2014-11-14 11:01:17,2014-12-14 11:01:17,39 days 17:19:19
3814,2015-06-19 19:46:38,2015-08-13 15:28:13,2015-06-29 15:28:13,2015-08-13 15:28:13,54 days 19:41:35
3815,2014-10-05 22:51:13,2014-12-07 16:20:53,2014-11-25 09:56:00,2014-12-08 02:00:00,63 days 03:08:47
3816,2018-04-25 15:03:49,2018-07-26 14:23:31,2018-06-26 14:23:31,2018-07-26 14:23:31,91 days 23:19:42
3817,2011-10-25 23:46:45,2012-01-29 07:59:00,2011-12-20 22:54:44,2012-01-29 07:59:00,95 days 08:12:15
3818,2013-06-04 19:48:47,2013-07-17 17:58:25,2013-06-17 17:58:25,2013-07-17 17:58:25,42 days 22:09:38
3819,2012-10-11 17:02:36,2012-11-18 20:00:31,2012-10-23 18:44:51,2012-11-18 20:00:00,38 days 02:57:24
3820,2017-09-18 01:15:00,2018-05-13 02:30:48,2018-04-03 02:30:48,2018-05-13 02:30:48,237 days 01:15:48
3821,2016-06-27 13:47:31,2016-09-30 16:24:02,2016-08-24 15:49:57,2016-09-30 16:24:00,95 days 02:36:29

In [0]:
ks201902.columns

Index(['backers_count', 'blurb', 'category', 'converted_pledged_amount',
       'country', 'created_at', 'creator', 'currency',
       'currency_trailing_code', 'current_currency', 'deadline', 'fx_rate',
       'goal', 'id', 'launched_at', 'location', 'name', 'photo', 'pledged',
       'profile', 'slug', 'spotlight', 'staff_pick', 'state',
       'state_changed_at', 'static_usd_rate', 'urls', 'usd_pledged',
       'usd_type'],
      dtype='object')

In [0]:
ks201902[["converted_pledged_amount","currency",  "currency_trailing_code","current_currency",  "pledged", "static_usd_rate", "usd_pledged", "usd_type"]]

,converted_pledged_amount,currency,currency_trailing_code,current_currency,pledged,static_usd_rate,usd_pledged,usd_type
0,205,USD,True,USD,205.00,1.000000,205.000000,domestic
1,6061,USD,True,USD,6061.00,1.000000,6061.000000,international
2,800,USD,True,USD,800.00,1.000000,800.000000,domestic
3,1484,USD,True,USD,1484.00,1.000000,1484.000000,domestic
4,1066,EUR,False,USD,941.00,1.155864,1087.667629,domestic
5,3871,GBP,False,USD,3010.00,1.300500,3914.505120,domestic
6,1110,USD,True,USD,1110.00,1.000000,1110.000000,international
7,4807,USD,True,USD,4807.00,1.000000,4807.000000,international
8,40368,USD,True,USD,40368.00,1.000000,40368.000000,international
9,57,EUR,False,USD,50.00,1.132671,56.633544,domestic
10,52,USD,True,USD,52.00,1.000000,52.000000,international
11,7770,USD,True,USD,7770.00,1.000000,7770.000000,international
12,1,USD,True,USD,1.00,1.000000,1.000000,domestic
13,6500,USD,True,USD,6500.00,1.000000,6500.000000,domestic
14,1138,EUR,False,USD,1000.00,1.168384,1168.384000,domestic
15,3511,USD,True,USD,3511.00,1.000000,3511.000000,domestic
16,1770,USD,True,USD,1770.85,1.000000,1770.850000,international
17,1378,CAD,True,USD,1721.00,0.807002,1388.850786,domestic
18,10390,USD,True,USD,10390.00,1.000000,10390.000000,international
19,45707,USD,True,USD,45707.00,1.000000,45707.000000,international
20,281,USD,True,USD,281.00,1.000000,281.000000,domestic
21,170,USD,True,USD,170.00,1.000000,170.000000,domestic
22,308,USD,True,USD,308.00,1.000000,308.000000,domestic
23,65,USD,True,USD,65.00,1.000000,65.000000,international
24,117240,USD,True,USD,117240.00,1.000000,117240.000000,international
25,325,USD,True,USD,325.45,1.000000,325.450000,domestic
26,108,USD,True,USD,108.00,1.000000,108.000000,domestic
27,7320,USD,True,USD,7320.00,1.000000,7320.000000,domestic
28,2,USD,True,USD,2.00,1.000000,2.000000,domestic
29,31,GBP,False,USD,26.00,1.318925,34.292060,domestic
...,...,...,...,...,...,...,...,...
3792,9291,USD,True,USD,9291.00,1.000000,9291.000000,domestic
3793,8173,USD,True,USD,8173.00,1.000000,8173.000000,international
3794,0,USD,True,USD,0.00,1.000000,0.000000,international
3795,5741,USD,True,USD,5741.00,1.000000,5741.000000,international
3796,0,GBP,False,USD,0.00,1.516726,0.000000,domestic
3797,431,USD,True,USD,431.00,1.000000,431.000000,domestic
3798,7037,USD,True,USD,7037.00,1.000000,7037.000000,international
3799,1413,CAD,True,USD,1809.00,0.772835,1398.057719,domestic
3800,11,USD,True,USD,11.00,1.000000,11.000000,international
3801,30303,USD,True,USD,30303.00,1.000000,30303.000000,domestic
3802,1320,AUD,True,USD,1506.00,0.932224,1403.928757,international
3803,43649,GBP,False,USD,33312.49,1.322996,44072.301680,international
3804,3210,USD,True,USD,3210.00,1.000000,3210.000000,international
3805,404,CAD,True,USD,535.00,0.750217,401.366298,domestic
3806,6016,USD,True,USD,6016.44,1.000000,6016.440000,domestic
3807,100,USD,True,USD,100.00,1.000000,100.000000,domestic
3808,501,USD,True,USD,501.00,1.000000,501.000000,international
3809,23207,GBP,False,USD,17799.00,1.277001,22729.333323,domestic
3810,300,USD,True,USD,300.00,1.000000,300.000000,domestic
3811,1,USD,True,USD,1.00,1.000000,1.000000,international
3812,0,USD,True,USD,0.00,1.000000,0.000000,international
3813,245,GBP,False,USD,156.00,1.577329,246.063380,domestic
3814,0,GBP,False,USD,0.00,1.574796,0.000000,international
3815,0,USD,True,USD,0.00,1.000000,0.000000,domestic
3816,1967,USD,True,USD,1967.00,1.000000,1967.000000,domestic
3817,2503,USD,True,USD,2503.00,1.000000,2503.000000,domestic
3818,2220,USD,True,USD,2220.00,1.000000,2220.000000,international
3819,3300,USD,True,USD,3300.00,1.000000,3300.000000,domestic
3820,20346,USD,True,USD,20346.00,1.000000,20346.000000,international
3821,2921,USD,True,USD,2921.00,1.000000,2921.000000,domestic

In [0]:
ks201902["current_currency"].value_counts()

USD    3818
HKD       2
GBP       1
CAD       1
Name: current_currency, dtype: int64

In [0]:
ks201902["usd_type"].value_counts()

domestic         2104
international    1714
Name: usd_type, dtype: int64

In [0]:
ks201902[ks201902["current_currency"] == "HKD"][["converted_pledged_amount","currency",  "currency_trailing_code","current_currency",  "pledged", "static_usd_rate", "usd_pledged", "usd_type"]]

,converted_pledged_amount,currency,currency_trailing_code,current_currency,pledged,static_usd_rate,usd_pledged,usd_type
3538,32922,GBP,False,HKD,3251.0,1.278344,4155.896604,NaN
3589,277452,USD,True,HKD,35352.0,1.000000,35352.000000,NaN

In [0]:
ks201902[ks201902["current_currency"] == "GBP"][["converted_pledged_amount","currency",  "currency_trailing_code","current_currency",  "pledged", "static_usd_rate", "usd_pledged", "usd_type"]]

,converted_pledged_amount,currency,currency_trailing_code,current_currency,pledged,static_usd_rate,usd_pledged,usd_type
103,696,USD,True,GBP,899.0,1.0,899.0,NaN

In [0]:
ks201902[ks201902["current_currency"] == "CAD"][["converted_pledged_amount","currency",  "currency_trailing_code","current_currency",  "pledged", "static_usd_rate", "usd_pledged", "usd_type"]]

,converted_pledged_amount,currency,currency_trailing_code,current_currency,pledged,static_usd_rate,usd_pledged,usd_type
942,1956,GBP,False,CAD,1148.0,1.28624,1476.603302,NaN

In [0]:
ks201902.loc[0][["converted_pledged_amount","currency",  "currency_trailing_code","current_currency",  "pledged", "static_usd_rate", "usd_pledged", "usd_type"]]

converted_pledged_amount         205
currency                         USD
currency_trailing_code          True
current_currency                 USD
pledged                          205
static_usd_rate                    1
usd_pledged                      205
usd_type                    domestic
Name: 0, dtype: object

In [0]:
ks201902.head()

,backers_count,blurb,category,converted_pledged_amount,country,created_at,creator,currency,currency_trailing_code,current_currency,...,profile,slug,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged,usd_type
0,4,Handmade glass trees that make a special Chris...,"{""id"":347,""name"":""Glass"",""slug"":""crafts/glass""...",205,US,1970-01-17 22:55:27.602,"{""id"":661261267,""name"":""Mark & Julie Glocke"",""...",USD,True,USD,...,"{""id"":2543897,""project_id"":2543897,""state"":""in...",glass-christmas-trees-and-glass-cross,False,False,failed,1466474764,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",205.000000,domestic
1,171,Perfect pair of Socks for any Adventurer! Sock...,"{""id"":34,""name"":""Tabletop Games"",""slug"":""games...",6061,US,1970-01-18 19:53:11.660,"{""id"":497057119,""name"":""Andy ""Cosmo-Joe"" Watki...",USD,True,USD,...,"{""id"":3498932,""project_id"":3498932,""state"":""in...",socks-of-speed-and-socks-of-elvenkind,True,False,successful,1542304740,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",6061.000000,international
2,9,This is a Series of 6 Books on Blessed Oscar A...,"{""id"":327,""name"":""Translations"",""slug"":""publis...",800,US,1970-01-17 14:29:44.826,"{""id"":267701790,""name"":""Convivium Press"",""slug...",USD,True,USD,...,"{""id"":1965582,""project_id"":1965582,""state"":""in...",the-complete-homilies-of-blessed-oscar-romero-...,False,False,failed,1439741591,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",800.000000,domestic
3,24,Prodeus makes self employment simple and intui...,"{""id"":342,""name"":""Web"",""slug"":""technology/web""...",1484,US,1970-01-18 06:59:57.043,"{""id"":973039847,""name"":""James Harr"",""is_regist...",USD,True,USD,...,"{""id"":2988723,""project_id"":2988723,""state"":""in...",prodeus-social-network-learning-community-micr...,False,False,failed,1498060876,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",1484.000000,domestic
4,62,"Welcome to Dungeon Corp LTD, a Dungeons and Dr...","{""id"":250,""name"":""Comic Books"",""slug"":""comics/...",1066,ES,1970-01-18 21:02:26.012,"{""id"":496847178,""name"":""Eternalverse"",""slug"":""...",EUR,False,USD,...,"{""id"":3533340,""project_id"":3533340,""state"":""in...",dungeon-corp-ltd-the-adventures-of-bob-and-tim,False,True,live,1547165608,1.155864,"{""web"":{""project"":""https://www.kickstarter.com...",1087.667629,domestic

In [0]:
json_cols = ["category", "creator"]
# TODO: add location. kept throwing error "Expecting ',' delimiter: line 1 column 31 (char 30)"
import ast

for col in json_cols:
  print(col)
  ks201902[col] = ks201902[col].fillna("")
  #ks201902[col] = ks201902[col].astype("str")
  ks201902[col] = ks201902[col].apply(ast.literal_eval)
  #ks201902[col] = ks201902[col].apply(json.loads)
  #ks201902[col] = ks201902[col].apply(json_normalize)
  
ks201902.head(3)
#ks201902["category"]

category

ValueError: ignored

In [0]:
!cd Data301FinalProject/ ;git add  *; git commit -m " ; git push